#!bin/bash
sudo cp ./.bashrc ~/.bashrc
sudo cp ./.vimrc ~/.vimrc
sudo cp ./tmux.conf /etc/tmux.conf
sudo apt-get install tmux neovm nodejs python3-dev cmake build-essential npm apache2
sudo git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
